// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAIBuJhJa18_pjh7LK7sQU8mNMdMIoW5E',
    appId: '1:428630551196:web:9126bd3c4c830652889b59',
    messagingSenderId: '428630551196',
    projectId: 'career-assistant-8e6eb',
    authDomain: 'career-assistant-8e6eb.firebaseapp.com',
    storageBucket: 'career-assistant-8e6eb.firebasestorage.app',
    measurementId: 'G-44JW1LY9TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK12PZIp6bKy25IbDU1qALeSdZXVjN-Uc',
    appId: '1:428630551196:android:d954e21f94e61cea889b59',
    messagingSenderId: '428630551196',
    projectId: 'career-assistant-8e6eb',
    storageBucket: 'career-assistant-8e6eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApK8RHmB7OzVXxjtzQtY1fMxgmqSVzi1U',
    appId: '1:428630551196:ios:c92d4eafce9882b4889b59',
    messagingSenderId: '428630551196',
    projectId: 'career-assistant-8e6eb',
    storageBucket: 'career-assistant-8e6eb.firebasestorage.app',
    iosBundleId: 'com.example.careerAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApK8RHmB7OzVXxjtzQtY1fMxgmqSVzi1U',
    appId: '1:428630551196:ios:c92d4eafce9882b4889b59',
    messagingSenderId: '428630551196',
    projectId: 'career-assistant-8e6eb',
    storageBucket: 'career-assistant-8e6eb.firebasestorage.app',
    iosBundleId: 'com.example.careerAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAIBuJhJa18_pjh7LK7sQU8mNMdMIoW5E',
    appId: '1:428630551196:web:a834207cc86c1ddf889b59',
    messagingSenderId: '428630551196',
    projectId: 'career-assistant-8e6eb',
    authDomain: 'career-assistant-8e6eb.firebaseapp.com',
    storageBucket: 'career-assistant-8e6eb.firebasestorage.app',
    measurementId: 'G-4R7M94DN53',
  );
}
